=== BRUCELLA2/mars-sim/mars-sim-core/src/main/resources/conf/dtd/crops.dtd
<!ELEMENT crop-configuration (carbon-dioxide-consumption-rate, oxygen-consumption-rate, water-consumption-rate, watt-to-photon-conversion-ratio, crop-list)>
<!ELEMENT carbon-dioxide-consumption-rate EMPTY>
<!ATTLIST carbon-dioxide-consumption-rate value CDATA #REQUIRED>
<!ELEMENT oxygen-consumption-rate EMPTY>
<!ATTLIST oxygen-consumption-rate value CDATA #REQUIRED>
<!ELEMENT water-consumption-rate EMPTY>
<!ATTLIST water-consumption-rate value CDATA #REQUIRED>
<!ELEMENT watt-to-photon-conversion-ratio EMPTY>
<!ATTLIST watt-to-photon-conversion-ratio value CDATA #REQUIRED>
<!ELEMENT crop-list (crop*)>
<!ELEMENT crop EMPTY>
<!ATTLIST crop name CDATA #REQUIRED>
<!ATTLIST crop growing-time CDATA #REQUIRED>
<!ATTLIST crop crop-category CDATA #REQUIRED>
<!ATTLIST crop life-cycle CDATA #IMPLIED>
<!ATTLIST crop edible-biomass CDATA #REQUIRED>
<!ATTLIST crop edible-water-content CDATA #REQUIRED>
<!ATTLIST crop inedible-biomass CDATA #REQUIRED>
<!ATTLIST crop daily-PAR CDATA #REQUIRED>

=== BRUCELLA2/mars-sim/mars-sim-core/src/main/resources/conf/crops.xml
<?xml version="1.0" encoding="UTF-8"?>

<!DOCTYPE crop-configuration SYSTEM "conf/dtd/crops.dtd">

<!-- Read References 1 to 25 at the bottom -->

<crop-configuration>

	<!-- The average amount of carbon dioxide (kg) needed by a crop per square meter area in each Martian Sol -->
	<!-- Default: 2.0 -->
	<carbon-dioxide-consumption-rate value ="2.0" />

	<!-- The average amount of oxygen (kg) needed by a crop per square meter area in each Martian Sol -->
	<!-- Default: 2.0 -->
	<oxygen-consumption-rate value="2.0" />

	<!-- The average amount of water (kg) consumed by a crop per square meter area in each Martian Sol -->
	<!-- Default: 5.0 -->
	<water-consumption-rate value="5.0" />

	<!-- The ratio of measured irradiance [ Wm^-2 to PPF on Mars. Useful for calculate the instantaneous PAR in Crop.java -->
	<!-- see http://physics.stackexchange.com/questions/52487/photometer-measured-irradiance-l-converted-to-photon-rate -->
    <!-- Default: 4.568 on Mar [in u mol / m2 /s / (W m^2)] (vs. 4.609 on Earth-->
	<watt-to-photon-conversion-ratio value="4.568" />

	<crop-list>

<!--	Note : see Reference 7

			growing-time : # of sols
			crop-category : the type of crop
			edible-biomass : [ gram / m^2 / day ]
			edible-water-content : in proportion of 1 (1 is 100%)
			inedible-biomass :  [ gram / m^2 / day ]
			daily-PAR : [ mol / m^2 / day ]; Note: not umol / m^2 / s
-->

		<!-- https://www.researchgate.net/publication/262910301_Phenological_growth_stages_of_edible_asparagus_Asparagus_officinalis_Codification_and_description_according_to_the_BBCH_scale -->

	   	<crop name="Blueberry"
	        growing-time="600"
	    	crop-category="fruits"
	    	edible-biomass="14"
	    	edible-water-content=".87"
	    	inedible-biomass="5"
	    	daily-PAR="25.92"
	    	/>
	    	<!-- http://www.nasa.gov/pdf/190544main_SFN_Appendices.pdf
	    	http://blueberries.ces.ncsu.edu/wp-content/uploads/2012/10/evaluating-the-profitability-of-blueberry-production.pdf
	    	http://homeguides.sfgate.com/long-blueberry-plants-produce-60750.html
	    	A blueberry bush is at least 2 or 3 years old before it is mature and established enough to bear fruit.
	    	6k - 8k per acre or ~10-14k per hectare
	    	The irrigated planting on good blueberry soil reaches a peak
			production of 8,000 pounds per acre

	    	TODO: multi-year plant
	    	 -->


		<crop name="Cabbage"
	 	  	growing-time="85.0"
	    	crop-category="leaves"
	    	edible-biomass="75.78"
	    	edible-water-content=".92"
	    	inedible-biomass="6.74"
	    	daily-PAR="17.28"
	    	/>

		<crop name="Carrot"	growing-time="74.83" crop-category="roots" life-cycle="biennial" 
	    	edible-biomass="40"	edible-water-content=".88" inedible-biomass="59.87" daily-PAR="32.4"
	    	/>

		<!--
		https://www.revistas.ufg.br/pat/article/download/42449/22580
		31 T to 120 T/ha
		
		http://smallfarms.oregonstate.edu/sites/default/files/growth_stage_descriptions_online_2014-08-25.pdf
		stages: seedling emergence, leaving, root development, harvest
		
		-->
		
		<crop name="Celery" growing-time="75.0" crop-category="stems"
	    	edible-biomass="103.27" edible-water-content=".90" inedible-biomass="11.47" daily-PAR="17.28" />
	    	
	    <!-- Celery Sampling & Growth Stages at http://agvita.com.au/pdf/sampling/Celery_GS_V2.pdf
	    
		-->

	  <crop name="Corn" growing-time="65" crop-category="grains"
	    	edible-biomass="12.77" edible-water-content=".76" inedible-biomass="37.0" daily-PAR="34.56" />

		<!--
		http://lib.dr.iastate.edu/cgi/viewcontent.cgi?article=4354&context=etd
		Corn stover is a broad term which describes all of the above ground biomass
		from the corn crop except the grain. This biomass is comprised of structural
		components including stalks, leaves, tassel, husk, and cob. The U.S. Department of
		Energy estimates that over 76 million metric tons of corn stover are available from the
		roughly 28 million hectares of corn produced each year (Perlack, 2005).  

		Worldwide, with a yield of over 5 T/ha . Production can be significantly higher in certain regions of the world;
		2009 forecasts for production in Iowa were 11614 kg/ha

		Use (11.6 + 5)/2 = 8.30 T/ha
		8.30*100/65 = 12.77 g/m2/d

		http://www.ent.iastate.edu/pest/cornborer/stages-corn-development
		http://www.ent.iastate.edu/pest/cornborer/insect/damage

		Corn Growth and Development, https://graincrops.ca.uky.edu/files/corngrowthstages_2011.pdf
		Chad Lee, Univ. of Kentucky, 2005-2011

		CORN DEVELOPMENT AND KEY GROWTH STAGES
		http://publications.tamu.edu/CORN_SORGHUM/PUB_Corn%20Development%20and%20Key%20Growth%20Stages.pdf
		Reproductive stage :
		silking, blister, milk, dough, dent, 1/2 maturity, black layer

		Field corn vs. Sweet corn
		Although field corn is used mostly to create other products, sweet corn can be used as well.
		Plastics are manufactured from 		both types of corn to replace petroleum-based products.
		These include batteries, packaging materials, plastic silverware and other plastic products
		(such as skin and hair care bottles), toothpaste, candles, shampoo and dozens of others.
		A corn-based fuel for transportation, ethanol, is added to gasoline and is sold at many gas stations.

 		-->

	   	<crop name="Cranberry"
	        growing-time="300"
	    	crop-category="fruits"
	    	edible-biomass="11"
	    	edible-water-content=".87"
	    	inedible-biomass="5"
	    	daily-PAR="25.92"
	    	/>
	    	<!-- http://www.umass.edu/cranberry/downloads/Homeowner's%20fact%20sheet%202010.pdf
	    	http://www.ecologynorth.ca/wp-content/uploads/2012/03/Stimulating-Commercial-Berry-Production-FINAL-FEB-2012.pdf
	    	Production from mature plants is about 11 tonnes per hectare.
	    	Well-managed bogs should produce 100 to 200 barrels of cranberries per acre,
	    	-->

	   	<crop name="Cucumber"
	        growing-time="60"
	    	crop-category="fruits"
	    	edible-biomass="40"
	    	edible-water-content=".90"
	    	inedible-biomass="10"
	    	daily-PAR="25.92"
	    	/>
	    	<!--
	    	http://www.sqm.com/en-us/productos/nutricionvegetaldeespecialidad/cultivos/pepino.aspx#tabs-2
	    	http://teca.fao.org/sites/default/files/technology_files/High%20yielding%20vegetable%20varieties.pdf
	    	-->


	    <crop name="Garlic"
	        growing-time="85"
	    	crop-category="bulbs"
	    	life-cycle="biennial"
	    	edible-biomass="9.41"
	    	edible-water-content=".59"
	    	inedible-biomass="0.5"
	    	daily-PAR="17.28"
	    	/>

	    	<!--
	    		4494-6495 kg/hectare from http://www.dpi.nsw.gov.au/__data/assets/pdf_file/0018/470025/Garlic-gross-margin-budget.pdf
	    		or 549 g/sq meter or .5 kg/sqm or 5 kg/10sqm for 10 sqm space,

	    		garlic about 6 to 10 tonnes/ha from https://www.indiaagronet.com/indiaagronet/crop%20info/onion.htm
	    		8T/ha = 8000 kg/ha or 800 g/m2
	    		800/85 = 9.41 g/m2/d

	    		79.7g/136g = 58.6% H20 from http://nutritiondata.self.com/facts/vegetables-and-vegetable-products/2446/2
	    		
	    		-->


	     <crop name="Ginger"
	        growing-time="180"
	    	crop-category="roots"
	    	edible-biomass="18"
	    	edible-water-content=".12"
	    	inedible-biomass="2"
	    	daily-PAR="17.28"
	    	/>
	    	<!-- http://faostat.fao.org/site/339/default.aspx
	    	http://agritech.tnau.ac.in/org_farm/orgfarm_ginger.html
	    	http://www.tis-gdv.de/tis_e/ware/gewuerze/ingwerfr/ingwerfr.htm
	   		1. Average yields in central Jamaica are 13-18 tonnes/ hectare
	    	2. Harvesting is done from the 6th month onwards.
	    	3.  TODO: making ginger Tea

	    	 -->

	    	<!-- http://en.wiki2.org/wiki/Quinoa
	    	http://ntrs.nasa.gov/archive/nasa/casi.ntrs.nasa.gov/19940015664.pdf
	    	https://www.hort.purdue.edu/newcrop/proceedings1996/V3-632.html
	    	1. The seed yield (often around 3 t/ha up to 5 t/ha) is comparable to wheat yields in the Andean areas.
	    	2. The plants are allowed to stand until they are dry and the grain has reached a moisture content below 10%.
	    	3. TODO:
	    	 -->


		<crop name="Green Bell Pepper"
			growing-time= "40"
			crop-category="fruits"
			edible-biomass= "50"
			edible-water-content= ".45"
			inedible-biomass="20"
	    	daily-PAR="25.92"
			/>

	    <crop name="Green Onion"
	    	growing-time="70.0"
	    	crop-category="spices"
	    	edible-biomass="81.82"
	    	edible-water-content=".89"
	    	inedible-biomass="10.0"
	     	daily-PAR="17.28"
	    	/>
	   	<!-- 1. Harvest between 70-90 days
	   			Ref : http://www.veggiegardener.com/veggies/green-onions/ 
	   			
		scallions, leeks, spring onions
	   			
	   			-->


	    <crop name="Kidney bean"
	    	growing-time="85.0"
	    	crop-category="legumes"
	    	edible-biomass="11.11"
	    	edible-water-content=".10"
	    	inedible-biomass="150.0"
	     	daily-PAR="25.92"
	    	/>

	    <crop name="Lettuce"
	    	growing-time="28.0"
	    	crop-category="leaves"
	    	edible-biomass="35"
	    	edible-water-content=".95"
	    	inedible-biomass="5"
	     	daily-PAR="17.28"
	     	/>
	    	<!-- see http://www.ba.ars.usda.gov/hb66/lettuce.pdf
	    	http://www.fieldrobotics.org/~ssingh/VF/Challenges_in_Vertical_Farming/Schedule_files/GIACOMELLI.pdf
	    	 10 kg / week yield for greenhouse  -->


		<crop name="Morel Mushroom"
	    	growing-time="15.0"
	    	crop-category="fungi"
	    	edible-biomass="35"
	    	edible-water-content=".35"
	    	inedible-biomass="2"
	    	daily-PAR="5"
	    	/>
	    	<!-- Mushrooms provide essential nutrients, including vitamin D and vitamin B-6.
	    	Morel Mushroom is also called MORCHELLA.
	    	https://www.sciencenews.org/article/morel-mushroom-may-grow-crop-its-own?mode=magazine&context=189396
	    	Strands of the thick-footed morel fungus serve as a highway for...six times as dense...common soil bacteria.
	      	-->

	  <crop name="White Mustard" growing-time="82.5" crop-category="leaves"
	    	edible-biomass="66.67" edible-water-content=".7" inedible-biomass="1.02" daily-PAR="34.56" />

		<!-- ~82.5 day from https://www.hort.purdue.edu/newcrop/afcm/mustard.html
