=== BRUCELLA2/mars-sim/mars-sim-core/src/main/resources/conf/dtd/quotations.dtd
<!ELEMENT quotation-list (quotation*)>
<!ELEMENT quotation EMPTY>
<!ATTLIST quotation name CDATA #REQUIRED>
<!ATTLIST quotation text CDATA #REQUIRED>

=== BRUCELLA2/mars-sim/mars-sim-core/src/main/resources/conf/quotations.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE quotation-list SYSTEM "conf/dtd/quotations.dtd">

  <!--Sources : -->
  <!--1. https://en.wikiquote.org/wiki/Robert_A._Heinlein -->
  <!--2. https://en.wikiquote.org/wiki/Wernher_von_Braun -->


<quotation-list>
  <!--Note: text must be less than xx letters in total -->
  
  <!-- Robert A. Heinlein -->

	<quotation name="Robert A. Heinlein" text="Never worry about theory as long as the machinery does what it's supposed to do." />
  <!-- Waldo & Magic, Inc. -->
  
	<quotation name="Robert A. Heinlein" text="An armed society is a polite society. Manners are good when one may have to back up his acts with his life." />
  <!-- Beyond This Horizon, Chapter 15, “Probably a blind alley—” (p. 147) -->

	<quotation name="Robert A. Heinlein" text="Never listen to newscasts. Saves wear and tear on the nervous system." />
  <!-- Red Planet, Chapter 2, “South Colony, Mars”  -->

	<quotation name="Robert A. Heinlein" text="Every law that was ever written opened up a new way to graft." />
  <!-- Red Planet, Chapter 4, “Lowell Academy”  -->

	<quotation name="Robert A. Heinlein" text="I found out a long time ago that you have to take some chances in this life. Otherwise you are just a vegetable, headed for the soup pot." />
  <!-- Red Planet, Chapter 10, “We’re Boxed In!”  -->

	<quotation name="Robert A. Heinlein" text="Take sides! Always take sides! You will sometimes be wrong — but the man who refuses to take sides must always be wrong." />
  <!-- Double Star -->

	<quotation name="Robert A. Heinlein" text="If you would know a man, observe how he treats a cat." />
  <!-- The Door Into Summer, Chapter 1 -->

	<quotation name="Robert A. Heinlein" text="I counted to ten slowly, using binary notation." />
  <!-- The Door Into Summer, Chapter 8 -->

	<quotation name="Robert A. Heinlein" text="'Die trying' is the proudest human thing" />
  <!-- Have Space Suit—Will Travel, Chapter 11 -->

	<quotation name="Robert A. Heinlein" text="When a fact came along, he junked theories that failed to match." />
  <!-- Have Space Suit—Will Travel, Chapter 12 -->

	<quotation name="Robert A. Heinlein" text="The best things in history are accomplished by people who get tired of being shoved around." />
  <!-- Have Space Suit—Will Travel, Chapter 12 -->

	<quotation name="Robert A. Heinlein" text="A rational anarchist believes that concepts, such as 'state' and 'society' and 'government' have no existence save as physically exemplified in the acts of self-responsible individuals." />
  <!-- The Moon Is a Harsh Mistress -->

	<quotation name="Robert A. Heinlein" text="I will accept the rules that you feel necessary to your freedom. I am free, no matter what rules surround me. If I find them tolerable, I tolerate them; if I find them too obnoxious, I break them. I am free because I know that I alone am morally responsible for everything I do." />
  <!-- The Moon Is a Harsh Mistress -->

	<quotation name="Robert A. Heinlein" text="There is no worse tyranny than to force a man to pay for what he does not want merely because you think it would be good for him." />
  <!-- TANSTAAFL -->

	<quotation name="Robert A. Heinlein" text="Boats and ships are female because they are beautiful, lovable, expensive and unpredictable." />
  <!-- I Will Fear No Evil, Chapter 26 -->

	<quotation name="Robert A. Heinlein" text="Progress doesn't come from early risers — progress is made by lazy men looking for easier ways to do things." />
  <!-- Time Enough for Love -->

	<quotation name="Robert A. Heinlein" text="A generation which ignores history has no past and no future." />
  <!-- Time Enough for Love -->

	<quotation name="Robert A. Heinlein" text="Do not handicap your children by making their lives easy." />
  <!-- Time Enough for Love -->

	<quotation name="Robert A. Heinlein" text="If you happen to be one of the fretful minority who can do creative work, never force an idea; you'll abort it if you do. Be patient and you'll give birth to it when the time is ripe. Learn to wait." />
  <!-- Time Enough for Love -->

	<quotation name="Robert A. Heinlein" text="Never underestimate the power of human stupidity." />
  <!-- Time Enough for Love -->

	<quotation name="Robert A. Heinlein" text="You can have peace. Or you can have freedom. Don't ever count on having both at once." />
  <!-- Time Enough for Love -->

	<quotation name="Robert A. Heinlein" text="You live and learn. Or you don't live long." />
  <!-- Time Enough for Love -->

	<quotation name="Robert A. Heinlein" text="Be wary of strong drink. It can make you shoot at tax collectors — and miss." />
  <!-- Time Enough for Love -->

	<quotation name="Robert A. Heinlein" text="A human being should be able to change a diaper, plan an invasion, conn a ship, design a building, write a sonnet, balance accounts, build a wall, comfort the dying, take orders, cooperate, act alone, solve equations, analyze a new problem, pitch manure, program a computer, cook a tasty meal, fight efficiently and die gallantly. Specialization is for insects." />
  <!-- Wernher von Braun quotes -->
  
	<quotation name="Wernher von Braun" text="Don't tell me that man doesn't belong out there. Man belongs wherever he wants to go and he'll do plenty well when he gets there." />
  <!-- Time magazine (17 February 1958) -->

	<quotation name="Wernher von Braun" text="We can lick gravity, but sometimes the paperwork is overwhelming." />
  <!-- On Bureaucracy, Chicago Sun Times, 10 July 1958, as quoted in Gaither's Dictionary of Scientific Quotations (2012, 2nd edition) by Carl C. Gaither and Alma E. Cavazos-Gaither, editors, p. 925 -->

	<quotation name="Wernher von Braun" text="My experiences with science led me to God. They challenge science to prove the existence of God. But must we really light a candle to see the sun?" />
  <!-- From a letter to the California State board of Education (14 September 1972) -->
  
	<quotation name="Wernher von Braun" text="It is in scientific honesty that I endorse the presentation of alternative theories for the origin of the universe, life and man in the science classroom. It would be an error to overlook the possibility that the universe was planned rather than happening by chance." />
  <!-- From a letter to the California State board of Education (14 September 1972) -->

	<quotation name="Wernher von Braun" text="Basic research is what I am doing when I don't know what I am doing." />
  <!-- In an interview in the New York Times, 16 December 1957 -->
  
  
  <!-- Others --> 
  
	<quotation name="Robert Louis Steenson" text="The Dog, and the Plough, and the Hunter, and all. And the star of the sailor, and Mars, These shone in the sky, and the pail by the wall. Would be half full of water and stars." />
	<!-- Escape at Bedtime" -->  
  
  	<quotation name="Mike Fincke, NASA Astronaut" text="We have some special space shampoo that doesn't require water, and it does a pretty good job. So at without a bath, we're still pretty good, and we don't smell too bad." />

  	<quotation name="Valery Ryumin" text="All the conditions necessary for murder are met if you shut 2 men in a cabin measuring 18'x20' and leave them together for 2 months." />
	  
  
</quotation-list>
